select PATIENT.FIRST_NAME, PATIENT.LAST_NAME, NURSE.WARD from PATIENT
	inner join IN_PATIENT on 
		PATIENT.PATIENT_ID=IN_PATIENT.PATIENT_ID 
	inner join NURSE on
		IN_PATIENT.NURSE=NURSE.NURSE_ID
	where 
		PATIENT.CITY like('Negombo')
		and 
		NURSE.WARD=1

/*
update PATIENT
	set CITY='NEGOMBO' where PATIENT_ID='PT00000002';

select * from PATIENT where PATIENT_ID='PT00000002';
*/
	