select PATIENT.PATIENT_ID,PATIENT.FIRST_NAME,PATIENT.LAST_NAME,count(APPOINTMENT_ID) as NUMBER_OF_APPOINTMENTS 
	from APPOINTMENT 
	inner join PATIENT on
		PATIENT.PATIENT_ID=APPOINTMENT.PATIENT_ID 
group by PATIENT.PATIENT_ID,PATIENT.FIRST_NAME,PATIENT.LAST_NAME